server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/forpay?serverTimezone=UTC
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tpl_
      id-type: auto